// Schema exports
export {
  esIndex,
  ESIndex,
  type IndexSettings,
} from './schema/index-builder.ts';

export {
  ESField,
  esText,
  esKeyword,
  esInteger,
  esLong,
  esShort,
  esByte,
  esDouble,
  esFloat,
  esHalfFloat,
  esScaledFloat,
  esDate,
  esBoolean,
  esNested,
  esObject,
  esGeoPoint,
  esGeoShape,
  esIp,
  esBinary,
  type ESFieldConfig,
} from './schema/fields/index.ts';

export {
  type ESFieldType,
  type InferDocument,
  type InferInsertDocument,
  type GeoPoint,
  type GeoShape,
  type TextFieldOptions,
  type KeywordFieldOptions,
  type NumericFieldOptions,
  type DateFieldOptions,
  type BooleanFieldOptions,
  type GeoPointFieldOptions,
  type GeoShapeFieldOptions,
  type NestedFieldOptions,
  type ObjectFieldOptions,
} from './schema/types.ts';

// Client exports
export {
  ElasticORM,
  Database,
  type ElasticORMConfig,
  type SchemaMap,
} from './client/index.ts';

export { ElasticError, ElasticConnection } from './client/connection.ts';

export {
  type IndexResponse,
  type IndexOptions,
  type GetResponse,
  type GetOptions,
  type UpdateResponse,
  type UpdateOptions,
  type DeleteResponse,
  type DeleteOptions,
  type BulkResponse,
  type BulkResponseItem,
  type BulkItemResult,
  type BulkOptions,
} from './client/operations/index.ts';

// Query exports
export { SearchBuilder } from './query/builder.ts';

export {
  eq,
  inValues,
  exists,
  ids,
  prefix,
  wildcard,
  regexp,
  fuzzy,
  range,
  gt,
  gte,
  lt,
  lte,
  match,
  matchPhrase,
  matchPhrasePrefix,
  multiMatch,
  queryString,
  simpleQueryString,
  bool,
  must,
  filter,
  should,
  mustNot,
  matchAll,
  matchNone,
  boosting,
  constantScore,
  disMax,
  nested,
  hasChild,
  hasParent,
  geoBoundingBox,
  geoDistance,
  geoPolygon,
  geoShape,
  type MatchOptions,
  type MatchPhraseOptions,
  type MatchPhrasePrefixOptions,
  type MultiMatchOptions,
  type RangeOptions,
} from './query/conditions/index.ts';

export {
  type QueryCondition,
  type SearchResponse,
  type SearchHit,
  type SortOption,
  type HighlightOptions,
  type SourceFilter,
} from './query/types.ts';

// Aggregation exports
export {
  terms,
  multiTerms,
  significantTerms,
  histogram,
  dateHistogram,
  autoDateHistogram,
  range as rangeAgg,
  dateRange,
  ipRange,
  filterAgg,
  filters,
  global,
  missing,
  sampler,
  nestedAgg,
  reverseNested,
  type TermsAggregationOptions,
  type HistogramAggregationOptions,
  type DateHistogramAggregationOptions,
  type CalendarInterval,
  type RangeBucketDefinition,
} from './aggregations/bucket/index.ts';

export {
  avg,
  sum,
  min,
  max,
  valueCount,
  cardinality,
  weightedAvg,
  medianAbsoluteDeviation,
  stats,
  extendedStats,
  stringStats,
  matrixStats,
  percentiles,
  percentileRanks,
  boxplot,
  topHits,
  topMetrics,
  type MetricAggregationOptions,
  type StatsAggregationOptions,
  type PercentilesAggregationOptions,
  type TopHitsAggregationOptions,
} from './aggregations/metric/index.ts';

export {
  type Aggregation,
  type AggregationResult,
  type TermsAggregationResult,
  type HistogramAggregationResult,
  type DateHistogramAggregationResult,
  type RangeAggregationResult,
  type FilterAggregationResult,
  type FiltersAggregationResult,
  type NestedAggregationResult,
  type MetricAggregationResult,
  type StatsAggregationResult,
  type ExtendedStatsAggregationResult,
  type PercentilesAggregationResult,
  type PercentileRanksAggregationResult,
  type TopHitsAggregationResult,
} from './aggregations/types.ts';

// Index management exports
export {
  createIndex,
  updateMapping,
  deleteIndex,
  indexExists,
  getIndex,
  getMapping,
  getSettings,
  updateSettings,
  refreshIndex,
  flushIndex,
  closeIndex,
  openIndex,
  addAlias,
  removeAlias,
  reindex,
  IndexManager,
  type IndexInfo,
  type CreateIndexResponse,
  type UpdateMappingResponse,
  type DeleteIndexResponse,
  type RefreshResponse,
  type FlushResponse,
} from './index-management/index.ts';
